<?php require_once( TEMPLATE_PATH . './header.phtml' ); ?>
<div class="weui-msg">
    <div class="weui-msg__icon-area"><i class="weui-icon-warn weui-icon_msg"></i></div>
    <div class="weui-msg__text-area">
        <h2 class="weui-msg__title">操作失败</h2>
        <p class="weui-msg__desc">您访问的页面并不合法,请点击<a href="javascript:void(0);">返回首页</a>重新操作</p>
    </div>
</div>
<?php require_once( TEMPLATE_PATH . './footer.phtml' ); ?>
