<?php require_once( TEMPLATE_PATH . './header.phtml' ); ?>
<div class="weui_msg">
    <div class="weui_icon_area"><i class="weui_icon_warn weui_icon_msg"></i></div>
    <div class="weui_text_area">
        <h2 class="weui_msg_title">操作失败</h2>
        <p class="weui_msg_desc">您访问的页面并不合法,请点击<a href="/profile">返回用户中心</a>重新操作</p>
    </div>
</div>
<?php require_once( TEMPLATE_PATH . './footer.phtml' ); ?>
