<?php require_once( TEMPLATE_PATH . './header.phtml' ); ?>
<div class="page__bd">
    <div class="weui-cells weui-cells_form">
        <div class="weui-cell">
            <div class="weui-cell__hd"><label class="weui-label">姓名</label></div>
            <div class="weui-cell__bd">
                <input class="weui-input" type="text" placeholder="请输入真实姓名">
            </div>
        </div>
        <div class="weui-cell">
            <div class="weui-cell__hd"><label class="weui-label">房间号</label></div>
            <div class="weui-cell__bd">
                <input class="weui-input" type="text" placeholder="比如:201">
            </div>
        </div>
        <div class="weui-cell">
            <div class="weui-cell__hd"><label class="weui-label">手机号</label></div>
            <div class="weui-cell__bd">
                <input class="weui-input" type="tel" placeholder="">
            </div>
        </div>
    </div>

    <div class="weui-btn-area">
        <a class="weui-btn weui-btn_primary" href="javascript:" id="saveStaffInfo">保存</a>
    </div>
</div>
<?php require_once( TEMPLATE_PATH . './footer.phtml' ); ?>
<script>
$(document).ready(function(){
});
</script>
