<?php require_once( TEMPLATE_PATH . './header.phtml' ); ?>
    <div class="weui_cells_title">问题描述</div>
    <div class="weui_cells weui_cells_form">
        <div class="weui_cell">
            <div class="weui_cell_bd weui_cell_primary">
                <textarea id="textarea" class="weui_textarea" placeholder="请输入文本" rows="5"></textarea>
                <div class="weui_textarea_counter"><span id="count">0</span>/<span id="count_max">250</span></div>
            </div>
        </div>
    </div>

    <div class="weui_btn_area">
        <a class="weui_btn weui_btn_primary" href="javascript:" id="saveIssueInfo">确定</a>
    </div>
<?php require_once( TEMPLATE_PATH . './footer.phtml' ); ?>
<script>
$(function(){
    var max = $('#count_max').text();
        $('#textarea').on('input', function(){
            var text = $(this).val();
            var len = text.length;
            $('#count').text(len);
            if(len > max){
                $(this).closest('.weui_cell').addClass('weui_cell_warn');
            }
        else{
            $(this).closest('.weui_cell').removeClass('weui_cell_warn');
        }
    });
})
</script>
