<?php require_once( TEMPLATE_PATH . './header.phtml' ); ?>
    <div class="weui_cells weui_cells_form">
        <div class="weui_cell">
            <div class="weui_cell_hd"><label class="weui_label">姓名</label></div>
            <div class="weui_cell_bd">
                <input class="weui_input" id="name" type="text" placeholder="请输入真实姓名">
            </div>
        </div>
        <div class="weui_cell">
            <div class="weui_cell_hd"><label class="weui_label">房间号</label></div>
            <div class="weui_cell_bd">
                <input class="weui_input" id="room" type="text" placeholder="比如:201">
            </div>
        </div>
        <div class="weui_cell">
            <div class="weui_cell_hd"><label class="weui_label">手机号</label></div>
            <div class="weui_cell_bd">
                <input class="weui_input" id="phone" type="tel" placeholder="">
            </div>
        </div>
    </div>

    <div class="weui_btn_area">
        <a class="weui_btn weui_btn_primary" href="javascript:" id="saveStaffInfo">确定</a>
    </div>

<?php require_once( TEMPLATE_PATH . './footer.phtml' ); ?>
<script>
$(document).ready(function(){
    $('#saveStaffInfo').click(function(){
        var data = {
            phone: $.trim($('#phone').val()),
            name: $.trim($('#name').val()),
            room: $.trim($('#room').val()),
        }
        if(empty(data.name)){
            $.toast("请输入真实姓名");
            return false;
        }
        if(empty(data.room)){
            $.toast("请输入房间号");
            return false;
        }
        if(!is_phone(data.phone)){
            $.toast("请输入合法的手机号");
            return false;
        }
        $.showLoading();
        $.ajax({
            type: 'post',
            url: '/profile/save',
            dataType: 'json',
            data: data,
            success: function (data) {
                $.hideLoading();
                if(data.status){
                    renderAjaxRespDiv({
                        status: true,
                        url: '/profile',
                        urltext: '返回用户中心',
                    });
                } else {
                    $.toast(data.msg);
                }
            }
        });
    });
});
</script>
