<?php require_once( TEMPLATE_PATH . './header.phtml' ); ?>
<?php require_once( TEMPLATE_PATH . './wxjssdk.phtml' ); ?>
    <div class="weui_cells_title">问题描述</div>
    <div class="weui_cells weui_cells_form">
        <div class="weui_cell" id="descriptionWrapper">
            <div class="weui_cell_bd weui_cell_primary">
                <textarea id="description" class="weui_textarea" placeholder="请输入文本" rows="5"></textarea>
                <div class="weui_textarea_counter"><span id="count">0</span>/<span id="count_max">100</span></div>
            </div>
        </div>
        <div class="weui_cell">
            <div class="weui_cell_bd weui_cell_primary">
              <div class="weui_uploader">
                <div class="weui_uploader_hd weui_cell">
                  <div class="weui_cell_bd weui_cell_primary">图片上传</div>
                  <div class="weui_cell_ft js_counter">0/6</div>
                </div>
                <div class="weui_uploader_bd">
                  <ul class="weui_uploader_files">
                    <!-- 预览图插入到这 --> </ul>
                  <div class="weui_uploader_input_wrp">
                    <a id="chooseImageBtn" class="weui_uploader_input js_file"></a></div>
                </div>
              </div>
            </div>
        </div>
    </div>
    <div class="weui_btn_area">
        <a class="weui_btn weui_btn_primary" href="javascript:" id="saveIssueInfo">确定</a>
    </div>
<?php require_once( TEMPLATE_PATH . './footer.phtml' ); ?>
<script>
$(function(){
    var max = $('#count_max').text();
        $('#description').on('input', function(){
            var text = $(this).val();
            var len = text.length;
            $('#count').text(len);
            if(len > max){
                $(this).closest('.weui_cell').addClass('weui_cell_warn');
            }
        else{
            $(this).closest('.weui_cell').removeClass('weui_cell_warn');
        }
    });

    $('#saveIssueInfo').click(function(){
        var data = {};
        data.description = $.trim( $('#description').val() );
        data.image_url = [];
        $('.weui_uploader_file').each(function(){
            data.image_url.push($(this).data('url'));
        });
        if($('#descriptionWrapper').hasClass('weui_cell_warn')){
            $.toast("问题描述超出字数限制");
            return false;
        }
        if(empty(data.description)){
            $.toast("请输入房间号");
            return false;
        }
        $.showLoading();
        $.ajax({
            type: 'post',
            url: '/issue/save',
            dataType: 'json',
            data: data,
            success: function (data) {
                $.hideLoading();
                if(data.status){
                    renderAjaxRespDiv({
                        status: true,
                        url: '/profile',
                        urltext: '返回用户中心',
                    });
                } else {
                    $.toast(data.msg);
                }
            }
        });
    });


});
wx.ready(function(){
    $('#chooseImageBtn').click(function(){
        var num = $('.weui_uploader_file').length;
        if(num >= 6){
            $.toast('您最多只能上传6张图片');
            return false;
        }
        wx.chooseImage({
            count: 6-num, // 默认9
            sizeType: ['original', 'compressed'], // 可以指定是原图还是压缩图，默认二者都有
            sourceType: ['album', 'camera'], // 可以指定来源是相册还是相机，默认二者都有
            success: function (res) {
                var localIds = res.localIds; // 返回选定照片的本地ID列表，localId可以作为img标签的src属性显示图片
                uploadImage(localIds);
            }
        });
        return false;
    });
});

// 微信不能同时上传多张图片,只能一个接一个上传
function uploadImage( localIds )
{
    if(localIds.length == 0){
        return false;
    }
    wx.uploadImage({
        localId: localIds[0], // 需要上传的图片的本地ID，由chooseImage接口获得
        isShowProgressTips: 1, // 默认为1，显示进度提示
        success: function (res) {
            var serverId = res.serverId; // 返回图片的服务器端ID
            // 显示出来
            wx.getLocalImgData({
                localId: localIds[0], // 图片的localID
                success: function (res) {
                    var localData = res.localData; // localData是图片的base64数据，可以用img标签显示
                    var $preview = $('<li class="weui_uploader_file" data-url="'+serverId+'" style="background-image:url(' + localData + ')"></li>');
                    $('.weui_uploader_files').append($preview);
                    var num = $('.weui_uploader_file').length;
                    $('.js_counter').html(num + '/6');
                    if( num >= 6 ){
                        $('.weui_uploader_input_wrp').addClass('hide');
                    }
                }
            });
            localIds.splice(0, 1);
            uploadImage( localIds );
        }
    });
}
</script>
