<?php require_once( TEMPLATE_PATH . './header.phtml' ); ?>
<?php require_once( TEMPLATE_PATH . './wxjssdk.phtml' ); ?>
<?php require_once( TEMPLATE_PATH . './qcloud.phtml' ); ?>
    <div class="weui_cells_title">问题描述</div>
    <div class="weui_cells weui_cells_form">
        <div class="weui_cell" id="descriptionWrapper">
            <div class="weui_cell_bd weui_cell_primary">
                <textarea id="description" class="weui_textarea" placeholder="请输入文本" rows="5"></textarea>
                <div class="weui_textarea_counter"><span id="count">0</span>/<span id="count_max">100</span></div>
            </div>
        </div>
        <div class="weui_cell">
            <div class="weui_cell_bd weui_cell_primary">
              <div class="weui_uploader">
                <div class="weui_uploader_hd weui_cell">
                  <div class="weui_cell_bd weui_cell_primary">图片上传</div>
                  <div class="weui_cell_ft js_counter">0/6</div>
                </div>
                <div class="weui_uploader_bd">
                  <ul class="weui_uploader_files" id="weui_uploader_images">
                    <!-- 预览图插入到这 --> </ul>
                  <div class="weui_uploader_input_wrp upload_image_action">
                    <a id="chooseImageBtn" class="weui_uploader_input js_file"></a></div>
                </div>
              </div>
            </div>
        </div>

        <div class="weui_cell">
            <div class="weui_cell_bd weui_cell_primary">
              <div class="weui_uploader">
                <div class="weui_uploader_hd weui_cell">
                  <div class="weui_cell_bd weui_cell_primary">视频上传</div>
                </div>
                <div class="weui_uploader_bd">
                  <ul class="weui_uploader_files" id="weui_uploader_videos">
                    </ul>
                  <div class="weui_uploader_input_wrp upload_video_action">
                      <form id="form1">
                    	<input id="chooseVideoInput" type="file" style="display:none;">
                    </form>
                    <a id="chooseVideoBtn" class="weui_uploader_input js_file"></a></div>
                </div>
              </div>
            </div>
        </div>
    </div>

    <div class="weui_btn_area">
        <input id="video_id" type="hidden" value="" />
        <a class="weui_btn weui_btn_primary" href="javascript:" id="saveIssueInfo">确定</a>
    </div>
<?php require_once( TEMPLATE_PATH . './footer.phtml' ); ?>
<script>
$(function(){
    var max = $('#count_max').text();
        $('#description').on('input', function(){
            var text = $(this).val();
            var len = text.length;
            $('#count').text(len);
            if(len > max){
                $(this).closest('.weui_cell').addClass('weui_cell_warn');
            }
        else{
            $(this).closest('.weui_cell').removeClass('weui_cell_warn');
        }
    });

    $('#saveIssueInfo').click(function(){
        var data = {};
        data.description = $.trim( $('#description').val() );
        data.image_url = [];
        data.video_id = $('#video_id').val();
        $('.weui_uploader_file').each(function(){
            data.image_url.push($(this).data('url'));
        });
        if($('#descriptionWrapper').hasClass('weui_cell_warn')){
            $.toast("问题描述超出字数限制");
            return false;
        }
        if(empty(data.description)){
            $.toast("请输入房间号");
            return false;
        }
        $.showLoading();
        $.ajax({
            type: 'post',
            url: '/issue/save',
            dataType: 'json',
            data: data,
            success: function (data) {
                $.hideLoading();
                if(data.status){
                    renderAjaxRespDiv({
                        status: true,
                        url: '/profile',
                        urltext: '返回用户中心',
                    });
                } else {
                    $.toast(data.msg);
                }
            }
        });
    });

    $('#chooseVideoBtn').click(function(){
        $('#chooseVideoInput').trigger('click');
    });

    // 上传视频相关
    $('#chooseVideoInput').on('change', function (e) {
		var videoFile = this.files[0];
        $.showLoading();
        var toastContent = $('.weui_toast_content');
        toastContent.text('已上传0%...');
		var resultMsg = qcVideo.ugcUploader.start({
    		videoFile: videoFile,
    		getSignature: getSignature,
    		allowAudio: 1,
            isTranscode: 1,
    		success: function(result){
    			if(result.type == 'video') {
    			} else if (result.type == 'cover') {
    			}
    		},
    		error: function(result){
    			if(result.type == 'video') {
                    $.toast('上传失败');
    			} else if (result.type == 'cover') {
    			}
    		},
    		progress: function(result){
    			if(result.type == 'video') {
                    toastContent.text('已上传'+Math.floor(result.shacurr*100)+'%...');
    			} else if (result.type == 'cover') {
    			}
    		},
    		finish: function(result){
                toastContent.text('视频转码中...');
                $.ajax({
                    type: 'post',
                    url: '/video/convert',
                    dataType: 'json',
                    data: {
                        file_id: result.fileId,
                    },
                    success: function (data) {
                        // 开始轮询
                        var it = setInterval(function(){
                            $.ajax({
                                type: 'get',
                                url: '/video/detail/' + result.fileId,
                                dataType: 'json',
                                success: function (data) {
                                    if(data.data.transcode_status == 1){
                                        $.hideLoading();
                                        clearInterval(it);
                                        $('.upload_video_action').addClass('hide');
                                        if(data.data.source.length > 0){
                                            for(var vk in data.data.source){
                                                if(parseInt(data.data.source[vk]['definition']) != 20){continue;}
                                                $('#weui_uploader_videos').append('<div id="insert_video_'+vk+'"  class="insert_video" style="width:100%; height:auto;margin-bottom:15px;"></div>');
                                                var player = new TcPlayer('insert_video_'+vk, {
                                                    "mp4": data.data.source[vk]['url'], //请替换成实际可用的播放地址
                                                    "autoplay" : false,      //iOS下safari浏览器，以及大部分移动端浏览器是不开放视频自动播放这个能力的
                                                    "coverpic" : {
                                                        'src': data.data.cover_url,
                                                        'style': 'cover',
                                                    },
                                                    "width" :  $('body').width()-30,//视频的显示宽度，请尽量使用视频分辨率宽度
                                                    "height" : parseInt( (data.data.source[vk]['vheight']/data.data.source[vk]['vwidth'])*($('body').width()-30) )//视频的显示高度，请尽量使用视频分辨率高度
                                                });
                                            }
                                        }
                                        $('#video_id').val(data.data.id);
                                    }
                                }
                            });
                        }, 2000);
                    }
                });

    		}
		});
		$('#form1')[0].reset();
	});



    $('#chooseImageBtn').click(function(){
        var num = $('.weui_uploader_file').length;
        if(num >= 6){
            $.toast('您最多只能上传6张图片');
            return false;
        }
        wx.ready(function(){
            wx.chooseImage({
                count: 6-num, // 默认9
                sizeType: ['original', 'compressed'], // 可以指定是原图还是压缩图，默认二者都有
                sourceType: ['album', 'camera'], // 可以指定来源是相册还是相机，默认二者都有
                success: function (res) {
                    var localIds = res.localIds; // 返回选定照片的本地ID列表，localId可以作为img标签的src属性显示图片
                    setTimeout(function(){
                        uploadImage(localIds);
                    }, 100);
                }
            });
        });
        return false;

    });

});


function showWxPreview( obj )
{
    var urls = [];
    $('.wxpreview').each(function(){
        urls.push($(this).data('src'));
    });
    var current = $(obj).data('src');
    wx.previewImage({
        current: current, // 当前显示图片的http链接
        urls: urls // 需要预览的图片http链接列表
    });
    return false;
}

// 微信不能同时上传多张图片,只能一个接一个上传
function uploadImage( localIds )
{
    if(localIds.length == 0){
        return false;
    }

    wx.uploadImage({
        localId: localIds[0], // 需要上传的图片的本地ID，由chooseImage接口获得
        isShowProgressTips: 1, // 默认为1，显示进度提示
        success: function (res) {
            var serverId = res.serverId; // 返回图片的服务器端ID
            // 显示出来
            wx.getLocalImgData({
                localId: localIds[0], // 图片的localID
                success: function (res) {
                    var localData = res.localData; // localData是图片的base64数据，可以用img标签显示
                    var $preview = $('<li class="weui_uploader_file wxpreview" data-src="'+localData+'" onclick="return showWxPreview(this);" data-url="'+serverId+'" style="background-image:url(' + localData + ')"></li>');
                    $('#weui_uploader_images').append($preview);
                    var num = $('.weui_uploader_file').length;
                    $('.js_counter').html(num + '/6');
                    if( num >= 6 ){
                        $('.upload_image_action').addClass('hide');
                    }
                }
            });
            localIds.splice(0, 1);
            uploadImage( localIds );
        }
    });
}
</script>
