    <!-- <div class="weui-footer">
        <p class="weui-footer-text">Copyright © 2017 江岸</p>
    </div> -->
    <div class="weui_tabbar " style="position:fixed;">
        <a href="/issue/status/0" class="weui_tabbar_item">
            <div class="weui_tabbar_icon">
                <img src="/assets/images/icon_nav_article.png" alt="">
            </div>
            <p class="weui_tabbar_label">问题</p>
        </a>
        <a href="/staffs/status/1" class="weui_tabbar_item">
            <div class="weui_tabbar_icon">
                <img src="/assets/images/icon_nav_cell.png" alt="">
            </div>
            <p class="weui_tabbar_label">成员</p>
        </a>
        <a href="/profile" class="weui_tabbar_item">
            <div class="weui_tabbar_icon">
                <img src="/assets/images/icon_nav_button.png" alt="">
            </div>
            <p class="weui_tabbar_label">我的</p>
        </a>
    </div>
</div>
</body>
</html>
