    <div class="page__ft j_bottom">
        <div class="weui-footer">
            <p class="weui-footer__text">Copyright © 2017 江岸</p>
        </div>
    </div>
</div>
<script src="/dist/zepto.min.js"></script>
<script type="text/javascript" src="https://res.wx.qq.com/open/js/jweixin-1.0.0.js"></script>
<script src="https://res.wx.qq.com/open/libs/weuijs/1.0.0/weui.min.js"></script>
</body>
</html>
