<!DOCTYPE html>
<html lang="zh-cmn-Hans">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=0">
    <title>我</title>
    <link rel="stylesheet" href="/assets/style/weui.css"/>
    <link rel="stylesheet" href="/assets/style/weui2.css"/>
    <link rel="stylesheet" href="/assets/style/weui3.css"/>
    <link rel="stylesheet" href="/assets/style/custom.css"/>
    <script src="/assets/zepto_weui.min.js"></script>
    <script src="/assets/php.js"></script>
    <script src="/assets/custom.js"></script>
</head>
<body ontouchstart class="page-bg">
<div id="content">
