<!DOCTYPE html>
<html lang="zh-cmn-Hans">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=0">
    <title><?php echo isset($title) ? $title : '工单系统'; ?></title>
    <link rel="stylesheet" href="/assets/style/weui.css"/>
    <link rel="stylesheet" href="/assets/style/weui2.css"/>
    <link rel="stylesheet" href="/assets/style/weui3.css"/>
    <link rel="stylesheet" href="/assets/style/custom.css"/>
    <script src="/assets/zepto_weui.min.js"></script>
    <script src="/assets/php.js"></script>
    <script src="/assets/picker.js"></script>
    <script src="/assets/custom.js"></script>
    <script src="http://res.wx.qq.com/open/js/jweixin-1.2.0.js"></script>
</head>
<body ontouchstart class="page-bg">
<div id="content">
<?php
global $app;
require_once SRC_PATH . "wechat-js-sdk/jssdk.php";
$wechatSettings = $app->getContainer()->get('settings')['wechat'];
$jssdk = new \JSSDK( $wechatSettings['appid'], $wechatSettings['appsecret'] );
$signPackage = $jssdk->GetSignPackage();
?>
<script>
wx.config({
    debug: true, // 开启调试模式,调用的所有api的返回值会在客户端alert出来，若要查看传入的参数，可以在pc端打开，参数信息会通过log打出，仅在pc端时才会打印。
    appId: '<?php echo $signPackage["appId"];?>',
    timestamp: <?php echo $signPackage["timestamp"];?>,
    nonceStr: '<?php echo $signPackage["nonceStr"];?>',
    signature: '<?php echo $signPackage["signature"];?>',
    jsApiList: [
        'checkJsApi',
		'onMenuShareTimeline',
		'onMenuShareAppMessage',
		'onMenuShareQQ',
		'onMenuShareWeibo',
		'hideMenuItems',
		'showMenuItems',
		'hideAllNonBaseMenuItem',
		'showAllNonBaseMenuItem',
		'translateVoice',
		'startRecord',
		'stopRecord',
		'onRecordEnd',
		'playVoice',
		'pauseVoice',
		'stopVoice',
		'uploadVoice',
		'downloadVoice',
		'chooseImage',
		'previewImage',
		'uploadImage',
		'downloadImage',
		'getNetworkType',
		'openLocation',
		'getLocation',
		'hideOptionMenu',
		'showOptionMenu',
		'closeWindow',
		'scanQRCode',
		'chooseWXPay',
		'openProductSpecificView',
		'addCard',
		'chooseCard',
		'openCard'
    ] // 必填，需要使用的JS接口列表，所有JS接口列表见附录2
});
</script>
