<?php require_once( TEMPLATE_PATH . './header.phtml' ); ?>
<?php require_once( TEMPLATE_PATH . './wxjssdk.phtml' ); ?>
<?php require_once( TEMPLATE_PATH . './qcloud.phtml' ); ?>

<div id="step1">
<div class="weui-form-preview">
    <div class="weui-form-preview-hd">
        <label class="weui-form-preview-label"><?php echo $issueStaffInfo['name']; ?></label>
        <em class="weui-form-preview-value"><?php echo $issueStaffInfo['room']; ?></em>
    </div>
    <div class="weui-form-preview-bd">
        <?php if($issueInfo['confirm_status'] == 1){ ?>
            <p>
                <label class="weui-form-preview-label f-green">预约号:</label>
                <span class="weui-form-preview-value f31 f-green"><?php echo formatServeNO( $issueInfo['serve_no'] ); ?></span>
            </p>
            <p>
                <label class="weui-form-preview-label f-green">预约时间:</label>
                <span class="weui-form-preview-value f-green"><?php echo $issueInfo['serve_time']; ?></span>
            </p>
        <?php } ?>
        <p>
            <label class="weui-form-preview-label">问题描述:</label>
            <span class="weui-form-preview-value"><?php echo $issueInfo['description']; ?></span>
        </p>
        <p>
            <label class="weui-form-preview-label">手机号:</label>
            <span class="weui-form-preview-value"><?php echo $issueStaffInfo['phone']; ?></span>
        </p>
        <p>
            <label class="weui-form-preview-label">创建时间:</label>
            <span class="weui-form-preview-value"><?php echo $issueInfo['create_time']; ?></span>
        </p>

        <div class="weui_cell_bd weui_cell_primary">
            <div class="weui_uploader">
                <div class="weui_uploader_hd weui_cell">问题图片:</div>
                <div class="weui_uploader_bd">
                    <?php if($issueInfo['image_url']){ ?>
                    <ul class="weui_uploader_files">
                        <?php foreach($issueInfo['image_url'] as $img){ ?>
                        <li data-href="<?php echo $img;?>"  class="weui_uploader_file wxpreview" style="background-image:url(<?php echo $img;?>);"></li>
                        <?php } ?>
                    </ul>
                    <?php } ?>
                </div>
            </div>
        </div>

        <div class="weui_cell_bd weui_cell_primary">
          <div class="weui_uploader">
            <div class="weui_uploader_hd weui_cell">视频:
            </div>
            <div class="weui_uploader_bd">
              <ul class="weui_uploader_files" id="weui_uploader_videos">



                </ul>
            </div>
          </div>
        </div>
    </div>
    <?php if($issueInfo['confirm_status'] == 0 && $belongTech){ ?>
    <div class="weui-form-preview-ft">
        <a id="confirmIssue" class="weui-form-preview-btn weui-form-preview-btn-primary" href="javascript:">确认预约</a>
    </div>
    <?php } ?>
</div>
</div>

<div id="step2" class="hide">
    <div class="weui_cells weui_cells_form ">
        <div class="weui_cell">
            <div class="weui_cell_hd"><label for="" class="weui_label">预约时间:</label></div>
            <div class="weui_cell_bd weui_cell_primary">
                <input class="weui_input" type="text" value="" id="serveTime" style="text-align:right;" readonly="">
            </div>
        </div>
    </div>
    <div class="weui_cells_tips">提交成功我们将会向提问者推送消息哦</div>
    <div class="weui_btn_area">
        <input type="hidden" id="issueID" value="<?=$issueInfo['id']?>" />
        <a id="confirmIssueAgain" href="javascript:" class="weui_btn weui_btn_primary">提交</a>
    </div>
</div>

<?php require_once( TEMPLATE_PATH . './footer.phtml' ); ?>
<script>


$(document).ready(function(){
    $('.wxpreview').click(function(){
        var urls = [];
        $('.wxpreview').each(function(){
            urls.push($(this).data('href'));
        });
        var current = $(this).data('href');
        wx.ready(function(){
            wx.previewImage({
                current: current, // 当前显示图片的http链接
                urls: urls // 需要预览的图片http链接列表
            });
        });
        return false;
    });

    // 加载视频信息
    <?php
        if(isset( $issueInfo['videoInfo']['source'] ) && !empty( isset( $issueInfo['videoInfo']['source'] ) ) ){
            foreach($issueInfo['videoInfo']['source'] as $k => $item){
                if($item['definition'] != 20){continue;}
    ?>
    $('#weui_uploader_videos').append('<div id="insert_video_<?=$k?>"  class="insert_video" style="width:100%; height:auto;margin-bottom:15px;"></div>');
    var player = new TcPlayer('insert_video_<?=$k?>', {
        "mp4": "<?=$item['url']?>", //请替换成实际可用的播放地址
        "autoplay" : false,      //iOS下safari浏览器，以及大部分移动端浏览器是不开放视频自动播放这个能力的
        "coverpic" : {
            'src': "<?=$issueInfo['videoInfo']['cover_url']?>",
            'style': 'cover',
        },
        "width" :  $('body').width()-30,//视频的显示宽度，请尽量使用视频分辨率宽度
        "height" : parseInt(<?=$item['vheight']/$item['vwidth']?>*($('body').width()-30))//视频的显示高度，请尽量使用视频分辨率高度
    });
    <?php
            }
        }else{
    ?>

    <?php
        }
    ?>
    $("#serveTime").datetimePicker({title:"选择日期时间",min:'2015-12-10',max:'2050-10-01'});
    $('#confirmIssue').click(function(){
        $('#step1').addClass('hide');
        $('#step2').removeClass('hide');
    });
    $('#confirmIssueAgain').click(function(){
        var data = {};
        data.serve_time = $('#serveTime').val();
        if(empty(data.serve_time)){
            $.toast('请填写预约时间');
            return false;
        }
        data.id = $('#issueID').val();
        $.showLoading();
        $.ajax({
            type: 'post',
            url: '/issue/confirm',
            dataType: 'json',
            data: data,
            success: function (data) {
                $.hideLoading();
                if(data.status){
                    renderAjaxRespDiv({
                        status: true,
                        url: '/issue/detail/<?=$issueInfo['id']?>',
                        urltext: '返回查看问题详情',
                    });
                } else {
                    $.toast(data.msg);
                }
            }
        });

    });
});
</script>
