<!DOCTYPE html>
<html lang="zh-cmn-Hans">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=0">
    <title>WeUI</title>
    <link rel="stylesheet" href="/style/weui.css"/>
    <link rel="stylesheet" href="/dist/example.css"/>
</head>
<body ontouchstart>
    <div class="page badge js_show">
        <div class="page__hd">
            <h1 class="page__title">Badge</h1>
            <p class="page__desc">徽章</p>
        </div>

        <div class="page__bd">
            <div class="weui-cells">
                <div class="weui-cell">
                    <div class="weui-cell__hd" style="position: relative;margin-right: 10px;">
                        <img src="images/pic_160.png" style="width: 50px;display: block">
                    </div>
                    <div class="weui-cell__bd">
                        <p><?php echo $staffInfo['name']; ?></p>
                        <p style="font-size: 13px;color: #888888;"><?php echo $staffInfo['department_name']; ?></p>
                    </div>
                </div>
                <div class="weui-cell">
                    <div class="weui-cell__bd">
                        <span style="vertical-align: middle">房间号</span>
                        <span class="weui-badge" style="margin-left: 5px;"><?php echo $staffInfo['department_name']; ?></span>
                    </div>
                    <div class="weui-cell__ft"></div>
                </div>
                <div class="weui-cell weui-cell_access">
                    <div class="weui-cell__bd">
                        <span style="vertical-align: middle">单行列表</span>
                        <span class="weui-badge" style="margin-left: 5px;">8</span>
                    </div>
                    <div class="weui-cell__ft">详细信息</div>
                </div>
                <div class="weui-cell weui-cell_access">
                    <div class="weui-cell__bd">
                        <span style="vertical-align: middle">单行列表</span>
                        <span class="weui-badge" style="margin-left: 5px;">New</span>
                    </div>
                    <div class="weui-cell__ft"></div>
                </div>
            </div>
        </div>

        <div class="page__ft j_bottom">
            <span>发达是否咖啡卡夫卡</span>
        </div>
    </div>


    <script src="/dist/zepto.min.js"></script>
    <script type="text/javascript" src="https://res.wx.qq.com/open/js/jweixin-1.0.0.js"></script>
    <script src="https://res.wx.qq.com/open/libs/weuijs/1.0.0/weui.min.js"></script>
</body>
</html>
