<?php require_once( TEMPLATE_PATH . './header.phtml' ); ?>

<div class="weui_panel">
<div class="weui_panel_hd">
<div class="weui_tab" style="height:44px;" id="tab5">
    <div class="weui_tab_nav">
        <a href="/staffs/status/1" class="weui_navbar_item weui_nav_green <?=$status==1?'bg_green':''?>"> 待审核 </a>
        <a href="/staffs/status/2" class="weui_navbar_item weui_nav_green <?=$status==2?'bg_green':''?>"> 已审核 </a>
    </div>
 </div>
 </div>
 </div>

 <?php if(!empty($staffList)){ ?>
 <div class="weui_panel weui_panel_access">
            <div class="weui_panel_bd">
                <?php foreach($staffList as $staff){ ?>
                <a href="/profile/id/<?=$staff['id']?>" class="weui_media_box weui_media_appmsg">
                    <div class="weui_media_hd">
                        <img class="weui_media_appmsg_thumb" src="<?=$staff['headimgurl']?>" alt="">
                    </div>
                    <div class="weui_media_bd">
                        <!-- <h4 class="weui_media_title"></h4>
                        <p class="weui_media_desc"></p>
                        <p class="weui_media_desc"></p> -->
                        <div class="weui_cell no_padding no_border">
                            <div class="weui_cell_bd weui_cell_primary">
                                <p>姓名</p>
                            </div>
                            <div class="weui_cell_ft"><?=$staff['name']?></div>
                        </div>
                        <div class="weui_cell no_padding no_border">
                            <div class="weui_cell_bd weui_cell_primary">
                                <p>房间号</p>
                            </div>
                            <div class="weui_cell_ft"><?=$staff['room']?></div>
                        </div>
                        <div class="weui_cell no_padding no_border">
                            <div class="weui_cell_bd weui_cell_primary">
                                <p>手机</p>
                            </div>
                            <div class="weui_cell_ft"><?=$staff['phone']?></div>
                        </div>
                    </div>
                </a>
                <?php } ?>
            </div>
        </div>
<?php }else{ ?>
    <div class="weui_msg hide" id="msg1" style="display: block; opacity: 1;">
        <div class="weui_text_area">
            <p class="weui_msg_desc">此栏目没有任何数据哦</p>
        </div>
    </div>
<?php } ?>

<?php require_once( TEMPLATE_PATH . './footer.phtml' ); ?>
